name: 'Lint'
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4
        with:
          run_install: |
            - recursive: true

      - name: Lint
        run: pnpm lint
